name: HBT-HERONS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        dm_only:    [ON, OFF]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build libhdf5-mpi-dev

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja -DHBT_MPI_TEST_FLAGS="--oversubscribe" -DHBT_DM_ONLY=${{ matrix.dm_only }}

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: cd build && ctest --output-on-failure
